version: '3'
services:
  sveltekit:
    container_name: sveltekit
    command: bash ./wait-for-it.sh iclosetdb:3306 -- ./push-and-run.sh
    ports:
      - 3000:3000
      - 24678:24678
      - 5173:5173
    depends_on:
      - iclosetdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules

  iclosetdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - icloset:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  icloset:
